apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w2ylej03e-go 
  janus-idp.io/tekton: w2ylej03e-go
  backstage.io/kubernetes-id: w2ylej03e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w2ylej03e-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml